export const services = [
  {
    category: "Brand Identity",
    name: "Brand Name Research",
    explanation: "Identifying a unique and memorable name for the brand.",
    required: true,
    oneTimeCost: 1000,
  },
  {
    category: "Brand Identity",
    name: "Domain Name",
    explanation: "Securing a researched based appropriate web address for the brand's online presence that is easy, google friendly and available.",
    required: true,
    oneTimeCost: 250,
  },
  {
    category: "Brand Strategy",
    name: "Market Research",
    explanation: "Analyzing market trends and competition to inform brand strategy.",
    required: false,
    oneTimeCost: 3500,
  },
  {
    category: "Brand Identity",
    name: "Brand Positioning",
    explanation: "Defining how the brand will stand out in the market.",
    required: false,
    oneTimeCost: 2500,
  },
  {
    category: "Brand Identity",
    name: "Brand Messaging",
    explanation: "Crafting the core message, tagline, and value proposition.",
    required: false,
    oneTimeCost: 2500,
  },
  {
    category: "Brand Strategy",
    name: "Customer Persona",
    explanation: "Developing detailed profiles of target customers.",
    required: false,
    oneTimeCost: 2500,
  },
  {
    category: "Brand Identity",
    name: "Logo Design, Color Palette & Typography (Brand Kit)",
    explanation: "Creating a memorable logo and selecting brand colors.",
    required: true,
    oneTimeCost: 2500,
  },
  {
    category: "Visual Design",
    name: "Packaging Design",
    explanation: "Designing attractive and functional packaging for products.",
    required: false,
    oneTimeCost: 5000,
  },
  {
    category: "Visual Design",
    name: "Label Design",
    explanation: "Crafting informative and compliant product labels.",
    required: false,
    oneTimeCost: 2500,
  },
  {
    category: "Website",
    name: "Website Design",
    explanation: "Developing a user-friendly and visually appealing website.",
    required: false,
    oneTimeCost: 2500,
  },
  {
    category: "Visual Design",
    name: "Social Media Graphics",
    explanation: "Designing consistent and engaging graphics for social media.",
    required: false,
    oneTimeCost: 2500,
  },
  {
    category: "Content Creation",
    name: "Photography",
    explanation: "Taking professional photos of products and team.",
    required: false,
    oneTimeCost: 4500,
  },
  {
    category: "Content Creation",
    name: "Copywriting",
    explanation: "Writing engaging and persuasive text for various platforms.",
    required: false,
    oneTimeCost: 2000,
  },
  {
    category: "Content Creation",
    name: "Copywriting (Website)",
    explanation: "Developing informative and engaging content for the website.",
    required: false,
    oneTimeCost: 1500,
  },
  {
    category: "Marketing Collateral",
    name: "Brochures and Flyers",
    explanation: "Designing print materials for promotions and events.",
    required: false,
    oneTimeCost: 7500,
  },
  {
    category: "Marketing Collateral",
    name: "Business Cards",
    explanation: "Creating professional business cards for networking.",
    required: false,
    oneTimeCost: 500,
  },
  {
    category: "Marketing Collateral",
    name: "Menus and Catalogs",
    explanation: "Designing comprehensive menus or product catalogs.",
    required: false,
    oneTimeCost: 4500,
  },
  {
    category: "Marketing Collateral",
    name: "Trade Show Material",
    explanation: "Developing banners, booths, and other materials for trade shows.",
    required: false,
    oneTimeCost: 9500,
  },
  {
    category: "Marketing Collateral",
    name: "Presentation Deck",
    explanation: "Creating slideshows for pitching to potential clients and partners.",
    required: false,
    oneTimeCost: 2500,
  },
  {
    category: "Digital Marketing",
    name: "Email Marketing",
    explanation: "Designing and sending newsletters and promotional emails.",
    required: false,
    oneTimeCost: 1500,
  },
  {
    category: "Public Relations",
    name: "Press Releases",
    explanation: "Writing and distributing newsworthy announcements to media outlets.",
    required: false,
    oneTimeCost: 2500,
  },
  {
    category: "Website",
    name: "Website Development",
    explanation: "Develop the website based on brand guidelines and content including G4, Pixel Setup.",
    required: false,
    oneTimeCost: 3500,
  },
  {
    category: "Brand Launch",
    name: "Launch Event",
    explanation: "Planning and executing an event to introduce the brand to the market.",
    required: false,
    oneTimeCost: 7500,
  },
];
